model_provider = "ict"
model = "gpt-5.5"
model_reasoning_effort = "high"
disable_response_storage = true
personality = "pragmatic"

[feature]
multi_agent = true

[model_providers.ict]
name = "ict"
base_url = "https://openai.1880148.xyz"
wire_api = "responses"
env_key = "ICT_KEY"
